### ISSUE TITLE
Can not deploy the code

### ISSUE THREAD

**Issue by rsmithdev6** [DouglasCAyers/sfdc-lead-conversion-record-types#1]
Deployment Started
Status: Queued 
Status: InProgress 
Status: InProgress 
Status: InProgress 
Status: Completed 
Deployment Complete
Failures:
classes/LeadConversionTriggerHelper.cls(142,18):Variable does not exist: Account.sObjectType
classes/LeadConversionTriggerHelperTest.cls(38,60):Method does not exist or incorrect signature: Account.sObjectType.getDescribe()
triggers/LeadConversionTrigger.trigger(34,5):Variable does not exist: LeadConversionTriggerHelper

**Comment by douglascayers** [comment]
Hi @rsmithdev6,

Thanks for the heads up. I did a test in a new developer org and was able to reproduce the problem. My unscientific testing makes me think that the recordTypeId field is not available on sobjects unless a custom record type exists.

Per that hypothesis, the problem is that the org you're deploying to likely does not have custom record types yet created for the Account object. Also, I imagine you may be trying to deploy into a new org and so there are no custom record types created for Contacts, Leads, or Opportunities either.

To fix the problem, please:
1. Make sure you have a Lead Process created (Setup | Leads | Lead Processes )
2. Make sure you have at least one Lead record type created other than 'master' (Setup | Leads | Record Types)
3. Make sure you have at least one Contact record type created other than 'master' (Setup | Contacts | Record Types)
4. Make sure you have at least one Account record type created other than 'master' (Setup | Accounts | Record Types)
5. Make sure you have at least one Opportunity Sales Process created (Setup | Opportunities | Sales Processes)
6. Make sure you have at least one Opportunity record type created other than 'master' (Setup | Opportunities | Record Types)

After I performed the above six steps in my developer org then I was able to deploy this code successfully.
