### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by trilame** [DouglasCAyers/sfdc-lead-conversion-record-types#2]
Hello,

First of all thanks for your useful job.

I deployed it in my sandbox to test, it worked perfectly.

Then I tried to deploy it on my production environment (still using GitHub Salesforce Deploy Tool) but it fails:

> Deployment CompleteTest failure, method: LeadConversionTriggerHelperTest.test_it_should_fail_when_missing_sobject_xref -- System.DmlException: Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Account_Record_Type_Name__c, Contact_Record_Type_Name__c]: [Account_Record_Type_Name__c, Contact_Record_Type_Name__c] stack Class.LeadConversionTriggerHelperTest.test_it_should_fail_when_missing_sobject_xref: line 85, column 1
> 
> Test failure, method: LeadConversionTriggerHelperTest.test_it_should_update_sobject_record_types -- System.NullPointerException: Attempt to de-reference a null object stack Class.LeadConversionTriggerHelperTest.test_it_should_update_sobject_record_types: line 137, column 1
> 
> Code coverage issue -- Average test coverage across all Apex Classes and Triggers is 72%, at least 75% test coverage is required.

Thank you in advance for your help!

**Comment by douglascayers** [comment]
Hi @trilame, thanks for reporting the issue. When I get a chance to dig into this I'll follow up.

**Comment by douglascayers** [comment]
Hi @trilame, I think I see the issue. The test code is looking for specific record type names which likely don't ever exist in other people's orgs. I believe this can be improved by just dynamically grabbing a record type from each of the objects so that existing record types in a customer's org are used and the test should pass. But... an even better solution is to use Process Builder!

Before Process Builder was released my only option was to go this route with apex code. I will write up a blog post how to do it with Process Builder so you don't have to wrangle with all this code =)

Thanks,

Doug

**Comment by douglascayers** [comment]
Hi @trilame, I've updated the code so the tests pass. You may want to check out my latest blog post on using Process Builder for a non-code solution: https://douglascayers.wordpress.com/2016/06/26/advanced-lead-conversion-with-process-builder/

**Comment by trilame** [comment]
Hello,

It works very well now! Thanks a lot for all of this.

I also checked the solution through the process builder, which looks great: maybe I'll try this one on another instance.
